titulo = str(input('qual o titulo: '))
autor = str(input('escritor: '))
comando = ['/give @p written_book{pages:[', "'", '"','] ,title:', ',author:', '}', titulo, autor] #estrutura do comando
l = str(input('cole aqui: ')) #livro em si.
tl = len(l) #total de caracteres do livro
print(tl)
qcn = (tl/256) #quantidade de cortes nessessarios
print(qcn)
qbn = 256 #quantidade de caracteres suportado
aux = 1 #variavel auxiliar
input('s? ')
for ndp in range(0, int(qcn)):
    qnd = (l[aux -1:qbn])
    comando.append(qnd)
    print(qnd)
    qbn = qbn + 256
    if tl > 255:
        aux = aux + 256
print('fim conferencia')
print(comando[0], comando[1], comando[2], comando[8],comando[2],
comando[1],',', comando[1], comando[2], comando[9],comando[2], comando[1],
',', comando[1], comando[2], comando[10],comando[2], comando[1],
',', comando[1], comando[2], comando[11],comando[2], comando[1],
',', comando[1], comando[2], comando[12],comando[2], comando[1],
',', comando[1], comando[2], comando[13],comando[2], comando[1],
',', comando[1], comando[2], comando[14],comando[2], comando[1],
',', comando[1], comando[2], comando[15],comando[2], comando[1],
',', comando[1], comando[2], comando[16],comando[2], comando[1],
',', comando[1], comando[2], comando[17],comando[2], comando[1],
',', comando[1], comando[2], comando[18],comando[2], comando[1],
',', comando[1], comando[2], comando[19],comando[2], comando[1],
',', comando[1], comando[2], comando[20],comando[2], comando[1],
',', comando[1], comando[2], comando[21],comando[2], comando[1],
',', comando[1], comando[2], comando[22],comando[2], comando[1],
',', comando[1], comando[2], comando[23],comando[2], comando[1],
',', comando[1], comando[2], comando[24],comando[2], comando[1],
',', comando[1], comando[2], comando[25],comando[2], comando[1],
',', comando[1], comando[2], comando[26],comando[2], comando[1],
',', comando[1], comando[2], comando[27],comando[2], comando[1],
',', comando[1], comando[2], comando[28],comando[2], comando[1],
',', comando[1], comando[2], comando[29],comando[2], comando[1],
',', comando[1], comando[2], comando[30],comando[2], comando[1],
',', comando[1], comando[2], comando[31],comando[2], comando[1],
',', comando[1], comando[2], comando[32],comando[2], comando[1],
',', comando[1], comando[2], comando[33],comando[2], comando[1],
',', comando[1], comando[2], comando[34],comando[2], comando[1],
',', comando[1], comando[2], comando[35],comando[2], comando[1],
',', comando[1], comando[2], comando[36],comando[2], comando[1],
',', comando[1], comando[2], comando[37],comando[2], comando[1],
',', comando[1], comando[2], comando[38],comando[2], comando[1],
',', comando[1], comando[2], comando[39],comando[2], comando[1],
',', comando[1], comando[2], comando[40],comando[2], comando[1],
',', comando[1], comando[2], comando[41],comando[2], comando[1],
',', comando[1], comando[2], comando[42],comando[2], comando[1],
',', comando[1], comando[2], comando[43],comando[2], comando[1],
',', comando[1], comando[2], comando[44],comando[2], comando[1],
',', comando[1], comando[2], comando[45],comando[2], comando[1],
',', comando[1], comando[2], comando[46],comando[2], comando[1],
',', comando[1], comando[2], comando[47],comando[2], comando[1],
',', comando[1], comando[2], comando[48],comando[2], comando[1],
',', comando[1], comando[2], comando[49],comando[2], comando[1],
',', comando[1], comando[2], comando[50],comando[2], comando[1],
',', comando[1], comando[2], comando[51],comando[2], comando[1],
',', comando[1], comando[2], comando[52],comando[2], comando[1],
',', comando[1], comando[2], comando[53],comando[2], comando[1],
',', comando[1], comando[2], comando[54],comando[2], comando[1],
',', comando[1], comando[2], comando[55],comando[2], comando[1],
',', comando[1], comando[2], comando[56],comando[2], comando[1],
',', comando[1], comando[2], comando[57],comando[2], comando[1],
',', comando[1], comando[2], comando[58],comando[2], comando[1],
',', comando[1], comando[2], comando[59],comando[2], comando[1],
',', comando[1], comando[2], comando[60],comando[2], comando[1],
',', comando[1], comando[2], comando[61],comando[2], comando[1],
',', comando[1], comando[2], comando[62],comando[2], comando[1],
',', comando[1], comando[2], comando[63],comando[2], comando[1],
',', comando[1], comando[2], comando[64],comando[2], comando[1],
',', comando[1], comando[2], comando[65],comando[2], comando[1],
',', comando[1], comando[2], comando[66],comando[2], comando[1],
',', comando[1], comando[2], comando[67],comando[2], comando[1],
',', comando[1], comando[2], comando[68],comando[2], comando[1],
',', comando[1], comando[2], comando[69],comando[2], comando[1],
',', comando[1], comando[2], comando[70],comando[2], comando[1],
',', comando[1], comando[2], comando[71],comando[2], comando[1],
',', comando[1], comando[2], comando[72],comando[2], comando[1],
',', comando[1], comando[2], comando[73],comando[2], comando[1],
',', comando[1], comando[2], comando[74],comando[2], comando[1],
',', comando[1], comando[2], comando[75],comando[2], comando[1],
',', comando[1], comando[2], comando[76],comando[2], comando[1],
',', comando[1], comando[2], comando[77],comando[2], comando[1],
',', comando[1], comando[2], comando[78],comando[2], comando[1],
',', comando[1], comando[2], comando[79],comando[2], comando[1],
',', comando[1], comando[2], comando[80],comando[2], comando[1],
',', comando[1], comando[2], comando[81],comando[2], comando[1],
',', comando[1], comando[2], comando[82],comando[2], comando[1],
',', comando[1], comando[2], comando[83],comando[2], comando[1],
',', comando[1], comando[2], comando[84],comando[2], comando[1],
',', comando[1], comando[2], comando[85],comando[2], comando[1],
',', comando[1], comando[2], comando[86],comando[2], comando[1],
',', comando[1], comando[2], comando[87],comando[2], comando[1],
',', comando[1], comando[2], comando[88],comando[2], comando[1],
',', comando[1], comando[2], comando[89],comando[2], comando[1],
',', comando[1], comando[2], comando[90],comando[2], comando[1],
',', comando[1], comando[2], comando[91],comando[2], comando[1],
',', comando[1], comando[2], comando[92],comando[2], comando[1],
',', comando[1], comando[2], comando[93],comando[2], comando[1],
',', comando[1], comando[2], comando[94],comando[2], comando[1],
',', comando[1], comando[2], comando[95],comando[2], comando[1],
',', comando[1], comando[2], comando[96],comando[2], comando[1],
',', comando[1], comando[2], comando[97],comando[2], comando[1],
',', comando[1], comando[2], comando[98],comando[2], comando[1],
',', comando[1], comando[2], comando[99],comando[2], comando[1],
',', comando[1], comando[2], comando[100],comando[2], comando[1],
',', comando[1], comando[2], comando[101],comando[2], comando[1],
',', comando[1], comando[2], comando[102],comando[2], comando[1],
',', comando[1], comando[2], comando[103],comando[2], comando[1],
',', comando[1], comando[2], comando[104],comando[2], comando[1],
',', comando[1], comando[2], comando[105],comando[2], comando[1],
',', comando[1], comando[2], comando[106],comando[2], comando[1],
',', comando[1], comando[2], comando[107],comando[2], comando[1],
comando[3],comando[2], comando[6],comando[2], comando[4],comando[2], comando[7],comando[2], comando[5])
